---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - name: set env
        run: echo "NOW=$(date +"%Y%m%d-%H%M%S")" >> $GITHUB_ENV

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: "Build"
        run: |
          npm install
          mkdir dist
          npm run build

      - name: "Install Zip"
        uses: "montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28"

      - name: "Zip"
        run: "zip -r ../release-${{ env.NOW }}.zip ./"
        working-directory: "dist"

      - name: "Release"
        uses: "ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "release-*.zip"
          commit: "main"
          generateReleaseNotes: true
          #makeLatest: 'legacy'
          name: "Development Build"
          prerelease: true
          removeArtifacts: true
          skipIfReleaseExists: false
          tag: "development"
          updateOnlyUnreleased: true
